// Estrutura da aplicação (Afeta todas as páginas)

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <header className="bg-blue-700 text-white p-4 shadow">
          <div className="max-w-6xl mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">App Aula TAC</h1>
            <nav>
              <a href="/user" className="mr-4 hover:underline">Lista</a>
              <a href="/user/form" className="hover:underline">Cadastro</a>
            </nav>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
